/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.casitaprojects.smartplayer;

/**
 *
 * @author gezer
 */
public class panelCola extends javax.swing.JPanel {

    /**
     * Creates new form panelCola
     */
    public panelCola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCola = new javax.swing.JTable();

        tblCola.setBackground(new java.awt.Color(51, 51, 51));
        tblCola.setForeground(new java.awt.Color(255, 255, 255));
        tblCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "TITULO", "ARTISTA", "ALBUM", "GENERO", "DURACION", "AÑO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblColaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblColaMouseClicked
        // Validamos si fueron 2 clics
        if (evt.getClickCount() == 2) {
            int filaSeleccionada = tblCola.getSelectedRow();
            if (filaSeleccionada != -1 && listaColaLocal != null) {

                Cancion cancionClickeada = listaColaLocal.get(filaSeleccionada);
                VentanaPrincipal ventana = (VentanaPrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);

                ventana.gestor.listaReproduccion.cargarLista(listaColaLocal, cancionClickeada);
                ventana.reproducirDesdeBiblioteca(cancionClickeada);
            }
        }
    }//GEN-LAST:event_tblColaMouseClicked

    // --- VARIABLE GLOBAL DEL PANEL ---
    private java.util.List<Cancion> listaColaLocal = new java.util.ArrayList<>();

    public void actualizarCola(VentanaPrincipal ventana) {
        listaColaLocal.clear();
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblCola.getModel();
        modelo.setRowCount(0); // Limpiamos la tabla visual

        int contador = 1;
        
        // Recorremos la Queue (Cola) y la pasamos a la tabla
        for (Cancion c : ventana.gestor.colaReproduccion) {
            listaColaLocal.add(c);
            modelo.addRow(new Object[]{
                contador++, 
                c.getTitulo(), 
                c.getArtista(), 
                c.getAlbum(), 
                c.getGenero(), 
                c.getDuracion(), 
                c.getAnio()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCola;
    // End of variables declaration//GEN-END:variables
}
