/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.casitaprojects.smartplayer;

// Importaciones necesarias para los mapas y listas
    import java.util.HashMap;
    import java.util.Map;
    import java.util.List;
    import javax.swing.ImageIcon;
    import java.awt.Image;
    import java.io.File;
    import org.jaudiotagger.audio.AudioFile;
    import org.jaudiotagger.audio.AudioFileIO;
    import org.jaudiotagger.tag.Tag;
/**
 *
 * @author gezer
 */
public class panelEstadistica extends javax.swing.JPanel {

    /**
     * Creates new form panelEstadistica
     */
    public panelEstadistica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCaratulaPopular = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblPlaylist = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblTotalHoras = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTimeAVL = new javax.swing.JLabel();
        lblTimeABB = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblTituloDup = new javax.swing.JLabel();
        lblRepetido = new javax.swing.JLabel();

        jLabel1.setText("CANCION POPULAR");

        lblCaratulaPopular.setText("S/C");

        lblTitulo.setText("TITULO CANCION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCaratulaPopular, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaratulaPopular, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitulo)
                .addContainerGap())
        );

        jLabel4.setText("ARTISTA POPULAR:");

        lblArtista.setText("ARTISTA");

        jLabel6.setText("GENERO POPULAR:");

        lblGenero.setText("GENERO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblArtista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGenero)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel8.setText("PLAYLIS GRANDE:");

        lblPlaylist.setText("FAVORITAS · 25 ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(lblPlaylist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel10.setText("PROMEDIO:");

        lblPromedio.setText("3m a 4m ");

        lblTotalHoras.setText("100  horas");
        lblTotalHoras.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalHoras)
                    .addComponent(lblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalHoras)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("BUSQUEDA AVL:");

        jLabel14.setText("BUSQUEDA ABB:");

        lblTimeAVL.setText("jLabel15");

        lblTimeABB.setText("jLabel16");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTimeAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTimeABB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimeAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTimeABB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jLabel17.setText("ARCHIVOS DUPLICADOS:");

        lblTituloDup.setText("TITULO DE CANCION");

        lblRepetido.setText("2 VECES REPETIDO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRepetido)
                    .addComponent(lblTituloDup, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(lblTituloDup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRepetido)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void calcularEstadisticas(VentanaPrincipal ventana) {
        List<Cancion> todas = ventana.listaTemporal; 
        
        if (todas == null || todas.isEmpty()) {
            lblTitulo.setText("Biblioteca Vacía");
            return;
        }

        // --- 1. PLAYLIST MÁS GRANDE ---
        Playlist playlistTop = null;
        int maxCanciones = -1;
        for (Playlist p : ventana.gestor.misPlaylists) {
            if (p.getCanciones().size() > maxCanciones) {
                maxCanciones = p.getCanciones().size();
                playlistTop = p;
            }
        }
        if (playlistTop != null) {
            lblPlaylist.setText(playlistTop.getNombre() + " · " + maxCanciones + " canciones");
        } else {
            lblPlaylist.setText("Sin playlists");
        }

        // --- 2. CÁLCULOS GLOBALES (Duplicados, Tiempos totales) ---
        long totalSegundos = 0;
        int maxRepsDuplicado = 1;
        String tituloDuplicado = "Ninguno";
        HashMap<String, Integer> mapaDuplicados = new HashMap<>(); 
        
        for (Cancion c : todas) {
            totalSegundos += convertirStringASegundos(c.getDuracion());
            
            // --- NUEVA LÓGICA DE DUPLICADOS (LA HUELLA FÍSICA DEFINITIVA) ---
            // Como Windows ensucia el texto agregando "- copia", comparamos el peso físico.
            // Dos archivos copiados pesarán EXACTAMENTE la misma cantidad de bytes.
            String huellaDigital = c.getTamanoBytes() + "_" + c.getDuracion();
            
            int reps = mapaDuplicados.getOrDefault(huellaDigital, 0) + 1;
            mapaDuplicados.put(huellaDigital, reps);
            
            if (reps > maxRepsDuplicado) {
                maxRepsDuplicado = reps;
                tituloDuplicado = c.getTitulo(); 
            }
        }
        
        // --- 3. PROMEDIOS ---
        long promedioSegundos = totalSegundos / todas.size();
        lblPromedio.setText(convertirSegundosAString(promedioSegundos));
        
        long horasTotales = totalSegundos / 3600;
        long minutosRestantes = (totalSegundos % 3600) / 60;
        lblTotalHoras.setText(horasTotales + " h " + minutosRestantes + " m");

        // --- 4. DUPLICADOS ---
        if (maxRepsDuplicado > 1) {
            lblTituloDup.setText(tituloDuplicado);
            lblRepetido.setText(maxRepsDuplicado + " VECES REPETIDO");
        } else {
            lblTituloDup.setText("Limpio");
            lblRepetido.setText("0 VECES REPETIDO");
        }

        // --- 5. RENDIMIENTO ABB vs AVL ---
        try {
            Cancion cancionPrueba = todas.get(todas.size() / 2); 
            
            long inicioABB = System.nanoTime();
            ventana.gestor.arbolABB.buscar(cancionPrueba.getTitulo());
            lblTimeABB.setText((System.nanoTime() - inicioABB) + " ns");

            long inicioAVL = System.nanoTime();
            ventana.gestor.arbolAVL.buscar(cancionPrueba.getTitulo());
            lblTimeAVL.setText((System.nanoTime() - inicioAVL) + " ns");
        } catch (Exception e) {
            lblTimeABB.setText("Error");
            lblTimeAVL.setText("Error");
        }

        // --- 6. HISTORIAL (Canción, Artista y Género Populares) ---
        cargarEstadisticasDelHistorial(todas);
    }

    // --- MÉTODOS AUXILIARES ---

    // --- 6. HISTORIAL (Canción, Artista y Género Populares simplificado) ---
    private void cargarEstadisticasDelHistorial(List<Cancion> todas) {
        if (todas == null || todas.isEmpty()) return;

        java.io.File archivo = new java.io.File("reproducciones.txt");
        Cancion topCancion = null;

        // Leemos el historial de reproducciones si existe
        if (archivo.exists()) {
            try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
                String lineaId;
                java.util.HashMap<String, Integer> conteoCanciones = new java.util.HashMap<>();

                while ((lineaId = br.readLine()) != null) {
                    lineaId = lineaId.trim(); // Limpieza clave de espacios en blanco
                    if (!lineaId.isEmpty()) {
                        conteoCanciones.put(lineaId, conteoCanciones.getOrDefault(lineaId, 0) + 1);
                    }
                }

                // Buscamos cuál fue la canción exacta más repetida
                if (!conteoCanciones.isEmpty()) {
                    String idMasEscuchado = obtenerLlaveConValorMaximo(conteoCanciones);
                    for (Cancion c : todas) {
                        if (c.getId().equals(idMasEscuchado)) {
                            topCancion = c;
                            break;
                        }
                    }
                }
            } catch (Exception e) {
                System.out.println("Error leyendo historial de reproducciones.");
            }
        }

        // Si el txt estaba vacío o no se encontró la canción, ponemos la primera de la lista por defecto
        if (topCancion == null) {
            topCancion = todas.get(0);
        }

        // --- LA LÓGICA DIRECTA QUE PEDISTE ---
        // Seteamos el Artista y Género sacándolos directamente de la canción ganadora
        lblArtista.setText(topCancion.getArtista() != null ? topCancion.getArtista() : "Desconocido");
        lblGenero.setText(topCancion.getGenero() != null ? topCancion.getGenero() : "Desconocido");

        // Mostramos el título y la carátula de esa misma canción
        mostrarDatosTopCancion(topCancion);
    }

    private void mostrarDatosTopCancion(Cancion top) {
        if (top == null) {
            lblTitulo.setText("Sin datos");
            return;
        }
        
        // FORZAMOS LA ACTUALIZACIÓN INMEDIATA DEL TÍTULO
        lblTitulo.setText(top.getTitulo());
        
        try {
            AudioFile audioFile = AudioFileIO.read(new File(top.getRutaArchivo()));
            Tag tag = audioFile.getTag();
            
            if (tag != null && tag.getFirstArtwork() != null) {
                byte[] imageData = tag.getFirstArtwork().getBinaryData();
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imageData);
                Image img = icon.getImage().getScaledInstance(92, 85, Image.SCALE_SMOOTH);
                lblCaratulaPopular.setIcon(new javax.swing.ImageIcon(img));
                lblCaratulaPopular.setText(""); 
            } else {
                lblCaratulaPopular.setIcon(null);
                lblCaratulaPopular.setText("S/C");
            }
        } catch (Exception e) {
            lblCaratulaPopular.setIcon(null);
            lblCaratulaPopular.setText("S/C");
        }
    }

    private String obtenerLlaveConValorMaximo(HashMap<String, Integer> mapa) {
        String llaveTop = "Desconocido";
        int max = -1;
        for (Map.Entry<String, Integer> entry : mapa.entrySet()) {
            if (entry.getValue() > max) {
                max = entry.getValue();
                llaveTop = entry.getKey();
            }
        }
        return llaveTop;
    }

    private int convertirStringASegundos(String tiempoFormato) {
        try {
            String[] partes = tiempoFormato.split(":");
            return (Integer.parseInt(partes[0]) * 60) + Integer.parseInt(partes[1]);
        } catch (Exception e) {
            return 0; 
        }
    }

    private String convertirSegundosAString(long totalSegundos) {
        return String.format("%02d:%02d", totalSegundos / 60, totalSegundos % 60);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblCaratulaPopular;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblPlaylist;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblRepetido;
    private javax.swing.JLabel lblTimeABB;
    private javax.swing.JLabel lblTimeAVL;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloDup;
    private javax.swing.JLabel lblTotalHoras;
    // End of variables declaration//GEN-END:variables
}
