/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.casitaprojects.smartplayer;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jaudiotagger.audio.AudioFile;
import org.jaudiotagger.audio.AudioFileIO;
import org.jaudiotagger.audio.AudioHeader;
import org.jaudiotagger.tag.FieldKey;
import org.jaudiotagger.tag.Tag;
/**
 *
 * @author gezer
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

        // --- VARIABLES GLOBALES DEL REPRODUCTOR ---
        GestorReproductor gestor = new GestorReproductor();
        ArrayList<Cancion> listaTemporal = new ArrayList<>(); // Guarda todo lo importado

        // Sacamos los paneles aquí afuera para poder usarlos en los botones
        panelBiblioteca vistaBiblioteca;
        panelPlaylist vistaPlaylist;
    
    
    public VentanaPrincipal() {
        initComponents();
        
        // Inicializamos los paneles
        vistaBiblioteca = new panelBiblioteca();
        vistaPlaylist = new panelPlaylist();
        
        pnlCentral.add(vistaBiblioteca, "CARTA_BIBLIOTECA");
        pnlCentral.add(vistaPlaylist, "CARTA_PLAYLIST");
    }
    
    // --- METODO RECURSIVO ---
    private void buscarCancionesRecursivo(File carpeta) {
        File[] archivos = carpeta.listFiles();
        if (archivos != null) {
            for (File archivo : archivos) {
                if (archivo.isDirectory()) {
                    buscarCancionesRecursivo(archivo); 
                } else if (archivo.getName().toLowerCase().endsWith(".mp3")) {
                    try {
                        AudioFile audioFile = AudioFileIO.read(archivo);
                        Tag tag = audioFile.getTag();
                        AudioHeader header = audioFile.getAudioHeader();
                        
                        String titulo = tag != null && tag.getFirst(FieldKey.TITLE) != null && !tag.getFirst(FieldKey.TITLE).isEmpty() ? tag.getFirst(FieldKey.TITLE) : archivo.getName().replace(".mp3", "");
                        String artista = tag != null && tag.getFirst(FieldKey.ARTIST) != null && !tag.getFirst(FieldKey.ARTIST).isEmpty() ? tag.getFirst(FieldKey.ARTIST) : "Desconocido";
                        String album = tag != null && tag.getFirst(FieldKey.ALBUM) != null && !tag.getFirst(FieldKey.ALBUM).isEmpty() ? tag.getFirst(FieldKey.ALBUM) : "Desconocido";
                        String genero = tag != null && tag.getFirst(FieldKey.GENRE) != null && !tag.getFirst(FieldKey.GENRE).isEmpty() ? tag.getFirst(FieldKey.GENRE) : "Desconocido";
                        String anio = tag != null && tag.getFirst(FieldKey.YEAR) != null && !tag.getFirst(FieldKey.YEAR).isEmpty() ? tag.getFirst(FieldKey.YEAR) : "Desconocido";
                        
                        int duracionSegundos = header.getTrackLength();
                        String duracionStr = String.format("%02d:%02d", duracionSegundos / 60, duracionSegundos % 60);
                        
                        Cancion nuevaCancion = new Cancion(titulo, artista, album, genero, duracionStr, archivo.length(), archivo.getAbsolutePath(), anio);
                        listaTemporal.add(nuevaCancion); 
                        
                    } catch (Exception e) {
                        System.out.println("Error metadatos en: " + archivo.getName());
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        btnBliblioteca = new javax.swing.JButton();
        lblSmart = new javax.swing.JLabel();
        btnPlaylist = new javax.swing.JButton();
        btnArbolABB = new javax.swing.JButton();
        btnAVL = new javax.swing.JButton();
        btnEstadistica = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnColaReproduccion = new javax.swing.JButton();
        btnEncriptacion = new javax.swing.JButton();
        TopBar = new javax.swing.JPanel();
        lblLupa = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnImportar = new javax.swing.JButton();
        PlayerInferior = new javax.swing.JPanel();
        lblCaratula = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblAlbum = new javax.swing.JLabel();
        tbtnLike = new javax.swing.JToggleButton();
        tbtnShuffle = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        tbtnBucle = new javax.swing.JToggleButton();
        sldTime = new javax.swing.JSlider();
        sldVolumen = new javax.swing.JSlider();
        lblVol = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pnlCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBliblioteca.setText("BIBLIOTECA");
        btnBliblioteca.setBorderPainted(false);
        btnBliblioteca.setContentAreaFilled(false);
        btnBliblioteca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBliblioteca.setFocusPainted(false);
        btnBliblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlibliotecaActionPerformed(evt);
            }
        });

        lblSmart.setText("SMART PLAYER");

        btnPlaylist.setText("PLAYLIST");
        btnPlaylist.setBorderPainted(false);
        btnPlaylist.setContentAreaFilled(false);
        btnPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlaylist.setFocusPainted(false);
        btnPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaylistActionPerformed(evt);
            }
        });

        btnArbolABB.setText("ARBOL ABB");
        btnArbolABB.setBorderPainted(false);
        btnArbolABB.setContentAreaFilled(false);
        btnArbolABB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArbolABB.setFocusPainted(false);
        btnArbolABB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbolABBActionPerformed(evt);
            }
        });

        btnAVL.setText("ARBOL AVL");
        btnAVL.setBorderPainted(false);
        btnAVL.setContentAreaFilled(false);
        btnAVL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAVL.setFocusPainted(false);
        btnAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAVLActionPerformed(evt);
            }
        });

        btnEstadistica.setText("ESTADISTICA");
        btnEstadistica.setBorderPainted(false);
        btnEstadistica.setContentAreaFilled(false);
        btnEstadistica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadistica.setFocusPainted(false);
        btnEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticaActionPerformed(evt);
            }
        });

        btnHistorial.setText("HISTORIAL");
        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorial.setFocusPainted(false);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnColaReproduccion.setText("EN COLA");
        btnColaReproduccion.setBorderPainted(false);
        btnColaReproduccion.setContentAreaFilled(false);
        btnColaReproduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnColaReproduccion.setFocusPainted(false);
        btnColaReproduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaReproduccionActionPerformed(evt);
            }
        });

        btnEncriptacion.setText("ENCRIPTACION");
        btnEncriptacion.setBorderPainted(false);
        btnEncriptacion.setContentAreaFilled(false);
        btnEncriptacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEncriptacion.setFocusPainted(false);
        btnEncriptacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncriptacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnColaReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEstadistica, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addComponent(btnAVL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnArbolABB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBliblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSmart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEncriptacion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSmart, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBliblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnArbolABB)
                .addGap(12, 12, 12)
                .addComponent(btnAVL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstadistica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnColaReproduccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEncriptacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TopBar.setForeground(new java.awt.Color(51, 51, 51));

        lblLupa.setBackground(new java.awt.Color(51, 51, 51));
        lblLupa.setText("Lupa");

        txtBuscar.setBackground(new java.awt.Color(51, 51, 51));
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setText("Buscar canciones, artistas, álbumes...");
        txtBuscar.setBorder(null);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnImportar.setText("IMPORTAR CARPETA");
        btnImportar.setBorderPainted(false);
        btnImportar.setContentAreaFilled(false);
        btnImportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImportar.setFocusPainted(false);
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLupa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLupa, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportar))
                .addContainerGap())
        );

        lblCaratula.setText("CARATULA");

        pnlDatos.setLayout(new javax.swing.BoxLayout(pnlDatos, javax.swing.BoxLayout.Y_AXIS));

        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("TITULO");
        pnlDatos.add(lblTitulo);

        lblArtista.setText("Artista");
        pnlDatos.add(lblArtista);

        lblAlbum.setText("Album");
        pnlDatos.add(lblAlbum);

        tbtnLike.setText("C");

        tbtnShuffle.setText("S");
        tbtnShuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnShuffleActionPerformed(evt);
            }
        });

        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        tbtnBucle.setText("B");
        tbtnBucle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnBucleActionPerformed(evt);
            }
        });

        lblVol.setText("jLabel4");

        lblDuracion.setText("00:00");

        lblTime.setText("00:00");

        javax.swing.GroupLayout PlayerInferiorLayout = new javax.swing.GroupLayout(PlayerInferior);
        PlayerInferior.setLayout(PlayerInferiorLayout);
        PlayerInferiorLayout.setHorizontalGroup(
            PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerInferiorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblCaratula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(tbtnLike, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayerInferiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addComponent(tbtnShuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbtnBucle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sldTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayerInferiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVol, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        PlayerInferiorLayout.setVerticalGroup(
            PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerInferiorLayout.createSequentialGroup()
                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCaratula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PlayerInferiorLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(tbtnLike))
                            .addGroup(PlayerInferiorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sldVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbtnShuffle)
                                        .addComponent(tbtnBucle)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDuracion)
                                    .addComponent(lblTime))))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlCentral.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(PlayerInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArbolABBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbolABBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArbolABBActionPerformed

    private void btnBlibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlibliotecaActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlCentral.getLayout();
        // Mostramos la carta usando el "Apodo" que le pusimos arriba
        layout.show(pnlCentral, "CARTA_BIBLIOTECA");
    }//GEN-LAST:event_btnBlibliotecaActionPerformed

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        javax.swing.JFileChooser explorador = new javax.swing.JFileChooser();
        explorador.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        
        int seleccion = explorador.showOpenDialog(this);
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            File carpetaSeleccionada = explorador.getSelectedFile();
            
            listaTemporal.clear(); // Limpiar lecturas anteriores
            buscarCancionesRecursivo(carpetaSeleccionada); // Leer MP3s
            
            // Llenar estructuras y medir
            long inicioABB = System.nanoTime();
            for (Cancion c : listaTemporal) { gestor.arbolABB.insertar(c); }
            long tiempoABB = System.nanoTime() - inicioABB;
            
            long inicioAVL = System.nanoTime();
            for (Cancion c : listaTemporal) { gestor.arbolAVL.insertar(c); }
            long tiempoAVL = System.nanoTime() - inicioAVL;

            long inicioHash = System.nanoTime();
            for (Cancion c : listaTemporal) { gestor.tablaHash.insertar(c); }
            long tiempoHash = System.nanoTime() - inicioHash;
            
            // --- ACTUALIZAMOS LA TABLA VISUAL ---
            vistaBiblioteca.actualizarTabla(listaTemporal);
            
            String mensaje = "¡Carga Completada!\n\n"
                           + "Canciones importadas: " + listaTemporal.size() + "\n\n"
                           + "⏱️ Tiempos de Inserción:\n"
                           + "Árbol ABB: " + tiempoABB + " ns\n"
                           + "Árbol AVL: " + tiempoAVL + " ns\n"
                           + "Tabla Hash: " + tiempoHash + " ns\n\n"
                           + (tiempoAVL > tiempoABB ? "(El AVL tardó más por las rotaciones)" : "");
                           
            JOptionPane.showMessageDialog(this, mensaje, "Análisis de Estructuras", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaylistActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlCentral.getLayout();
        // Aquí llamamos a la carta de la playlist usando el apodo exacto
        layout.show(pnlCentral, "CARTA_PLAYLIST");
    }//GEN-LAST:event_btnPlaylistActionPerformed

    private void btnAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAVLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAVLActionPerformed

    private void btnEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstadisticaActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnColaReproduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaReproduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColaReproduccionActionPerformed

    private void btnEncriptacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncriptacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncriptacionActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String textoBusqueda = txtBuscar.getText().trim();
        
        // Si borra el texto y da Enter, le mostramos toda la biblioteca de nuevo
        if (textoBusqueda.isEmpty() || textoBusqueda.equals("Buscar canciones, artistas, álbumes...")) {
            vistaBiblioteca.actualizarTabla(listaTemporal);
            return;
        }

        // Buscar en la Tabla Hash
        List<Cancion> resultados = gestor.tablaHash.buscar(textoBusqueda);

        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna canción para: " + textoBusqueda, "Sin resultados", JOptionPane.WARNING_MESSAGE);
        } else {
            // Actualizar la tabla solo con las canciones encontradas
            vistaBiblioteca.actualizarTabla(resultados);
            
            // Forzar a que la pantalla se pase a la biblioteca para ver los resultados
            java.awt.CardLayout layout = (java.awt.CardLayout) pnlCentral.getLayout();
            layout.show(pnlCentral, "CARTA_BIBLIOTECA");
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        MotorReproductor motor = MotorReproductor.getInstancia();
        
        if (motor.estaPausado()) {
            motor.reanudar();
            btnPlay.setText("||"); // Cambia icono a Pausa
        } else {
            motor.pausar();
            btnPlay.setText("PLAY"); // Cambia icono a Play
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Cancion anterior = gestor.listaReproduccion.obtenerAnterior();
        
        if (anterior != null) {
            reproducirDesdeBiblioteca(anterior);
            resaltarFilaEnTabla(anterior); // Para que se mueva la selección visual
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // Le pasamos el estado del botón Shuffle (true o false)
        Cancion siguiente = gestor.listaReproduccion.obtenerSiguiente(tbtnShuffle.isSelected());
        
        if (siguiente != null) {
            reproducirDesdeBiblioteca(siguiente);
            resaltarFilaEnTabla(siguiente); // Para que se mueva la selección visual
    }//GEN-LAST:event_btnNextActionPerformed
    }
    
    private void tbtnShuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnShuffleActionPerformed
        if (tbtnShuffle.isSelected()) {
            // Se pinta de verde estilo Spotify cuando se activa
            tbtnShuffle.setBackground(new java.awt.Color(30, 215, 96)); 
            tbtnShuffle.setForeground(java.awt.Color.WHITE);
            System.out.println("🔀 Modo Aleatorio: ACTIVADO");
        } else {
            // Regresa a su color normal cuando se desactiva
            tbtnShuffle.setBackground(new javax.swing.JButton().getBackground()); 
            tbtnShuffle.setForeground(java.awt.Color.BLACK);
            System.out.println("➡️ Modo Secuencial: ACTIVADO");
        }
    }//GEN-LAST:event_tbtnShuffleActionPerformed

    private void tbtnBucleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnBucleActionPerformed
        if (tbtnBucle.isSelected()) {
            // Se pinta de verde cuando se activa
            tbtnBucle.setBackground(new java.awt.Color(30, 215, 96));
            tbtnBucle.setForeground(java.awt.Color.WHITE);
            System.out.println("🔁 Modo Bucle: ACTIVADO");
        } else {
            // Regresa a su color normal
            tbtnBucle.setBackground(new javax.swing.JButton().getBackground());
            tbtnBucle.setForeground(java.awt.Color.BLACK);
            System.out.println("➡️ Modo Bucle: DESACTIVADO");
        }
    }//GEN-LAST:event_tbtnBucleActionPerformed

    // --- METODO PARA REPRODUCIR Y ACTUALIZAR UI ---
    public void reproducirDesdeBiblioteca(Cancion cancion) {
        
        // 1. Encendemos la música
        MotorReproductor.getInstancia().reproducirCancion(cancion.getRutaArchivo());
        
        // 2. Actualizamos los textos del panel inferior
        lblTitulo.setText(cancion.getTitulo());
        lblArtista.setText(cancion.getArtista());
        lblAlbum.setText(cancion.getAlbum());
        lblDuracion.setText(cancion.getDuracion());
        lblTime.setText("00:00"); // Reiniciamos el contador
        
        // Cambiamos el texto del botón Play para que diga PAUSE o cambie de icono
        btnPlay.setText("||"); 
        
        // 3. Extraemos la carátula
        try {
            AudioFile audioFile = AudioFileIO.read(new File(cancion.getRutaArchivo()));
            Tag tag = audioFile.getTag();
            
            if (tag != null && tag.getFirstArtwork() != null) {
                // Si tiene foto, la convertimos a imagen
                byte[] imageData = tag.getFirstArtwork().getBinaryData();
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imageData);
                // La redimensionamos al tamaño de tu lblCaratula
                java.awt.Image img = icon.getImage().getScaledInstance(lblCaratula.getWidth(), lblCaratula.getHeight(), java.awt.Image.SCALE_SMOOTH);
                
                lblCaratula.setIcon(new javax.swing.ImageIcon(img));
                lblCaratula.setText(""); // Borramos el texto
            } else {
                // Si no tiene foto, la dejamos limpia (luego le puedes poner una de disco por defecto)
                lblCaratula.setIcon(null);
                lblCaratula.setText("Sin Portada");
            }
        } catch (Exception e) {
            lblCaratula.setIcon(null);
            lblCaratula.setText("Error Portada");
        }
    }
    
    // Este método busca la canción en la tabla y la resalta automáticamente
    public void resaltarFilaEnTabla(Cancion cancionActual) {
        
        // ¡AQUÍ ESTÁ EL CAMBIO! Usamos el Getter que acabamos de crear
        javax.swing.JTable tabla = vistaBiblioteca.getTablaBiblioteca(); 
        
        for (int i = 0; i < tabla.getRowCount(); i++) {
            String tituloFila = tabla.getValueAt(i, 1).toString();
            if (tituloFila.equals(cancionActual.getTitulo())) {
                tabla.setRowSelectionInterval(i, i);
                break;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PlayerInferior;
    private javax.swing.JPanel SideBar;
    private javax.swing.JPanel TopBar;
    private javax.swing.JButton btnAVL;
    private javax.swing.JButton btnArbolABB;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBliblioteca;
    private javax.swing.JButton btnColaReproduccion;
    private javax.swing.JButton btnEncriptacion;
    private javax.swing.JButton btnEstadistica;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlaylist;
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblCaratula;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblLupa;
    private javax.swing.JLabel lblSmart;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVol;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JSlider sldTime;
    private javax.swing.JSlider sldVolumen;
    private javax.swing.JToggleButton tbtnBucle;
    private javax.swing.JToggleButton tbtnLike;
    private javax.swing.JToggleButton tbtnShuffle;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
