/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.casitaprojects.smartplayer;

/**
 *
 * @author gezer
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        // 1. Instanciamos tu nuevo JPanel Form
        panelBiblioteca vistaBiblioteca = new panelBiblioteca();
        
        // 2. Lo agregamos a tu PanelCentral y le ponemos un "Apodo"
        pnlCentral.add(vistaBiblioteca, "CARTA_BIBLIOTECA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        btnBliblioteca = new javax.swing.JButton();
        lblSmart = new javax.swing.JLabel();
        btnPlaylist = new javax.swing.JButton();
        btnArbolABB = new javax.swing.JButton();
        btnAVL = new javax.swing.JButton();
        btnEstadistica = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnColaReproduccion = new javax.swing.JButton();
        btnEncriptacion = new javax.swing.JButton();
        TopBar = new javax.swing.JPanel();
        lblLupa = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnImportar = new javax.swing.JButton();
        PlayerInferior = new javax.swing.JPanel();
        lblCaratula = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblAlbum = new javax.swing.JLabel();
        tbtnLike = new javax.swing.JToggleButton();
        tbtnShuffle = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnBucle = new javax.swing.JToggleButton();
        sldTime = new javax.swing.JSlider();
        sldVolumen = new javax.swing.JSlider();
        lblVol = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pnlCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBliblioteca.setText("BIBLIOTECA");
        btnBliblioteca.setBorderPainted(false);
        btnBliblioteca.setContentAreaFilled(false);
        btnBliblioteca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBliblioteca.setFocusPainted(false);
        btnBliblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlibliotecaActionPerformed(evt);
            }
        });

        lblSmart.setText("SMART PLAYER");

        btnPlaylist.setText("PLAYLIST");
        btnPlaylist.setBorderPainted(false);
        btnPlaylist.setContentAreaFilled(false);
        btnPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlaylist.setFocusPainted(false);

        btnArbolABB.setText("ARBOL ABB");
        btnArbolABB.setBorderPainted(false);
        btnArbolABB.setContentAreaFilled(false);
        btnArbolABB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArbolABB.setFocusPainted(false);
        btnArbolABB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbolABBActionPerformed(evt);
            }
        });

        btnAVL.setText("ARBOL AVL");
        btnAVL.setBorderPainted(false);
        btnAVL.setContentAreaFilled(false);
        btnAVL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAVL.setFocusPainted(false);

        btnEstadistica.setText("ESTADISTICA");
        btnEstadistica.setBorderPainted(false);
        btnEstadistica.setContentAreaFilled(false);
        btnEstadistica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadistica.setFocusPainted(false);

        btnHistorial.setText("HISTORIAL");
        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorial.setFocusPainted(false);

        btnColaReproduccion.setText("EN COLA");
        btnColaReproduccion.setBorderPainted(false);
        btnColaReproduccion.setContentAreaFilled(false);
        btnColaReproduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnColaReproduccion.setFocusPainted(false);

        btnEncriptacion.setText("ENCRIPTACION");
        btnEncriptacion.setBorderPainted(false);
        btnEncriptacion.setContentAreaFilled(false);
        btnEncriptacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEncriptacion.setFocusPainted(false);

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnColaReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEstadistica, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addComponent(btnAVL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnArbolABB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBliblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSmart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEncriptacion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSmart, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBliblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnArbolABB)
                .addGap(12, 12, 12)
                .addComponent(btnAVL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstadistica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnColaReproduccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEncriptacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TopBar.setForeground(new java.awt.Color(51, 51, 51));

        lblLupa.setBackground(new java.awt.Color(51, 51, 51));
        lblLupa.setText("Lupa");

        txtBuscar.setBackground(new java.awt.Color(51, 51, 51));
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setText("Buscar canciones, artistas, álbumes...");
        txtBuscar.setBorder(null);

        btnImportar.setText("IMPORTAR CARPETA");
        btnImportar.setBorderPainted(false);
        btnImportar.setContentAreaFilled(false);
        btnImportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImportar.setFocusPainted(false);
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLupa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLupa, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportar))
                .addContainerGap())
        );

        lblCaratula.setText("CARATULA");

        pnlDatos.setLayout(new javax.swing.BoxLayout(pnlDatos, javax.swing.BoxLayout.Y_AXIS));

        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("TITULO");
        pnlDatos.add(lblTitulo);

        lblArtista.setText("Artista");
        pnlDatos.add(lblArtista);

        lblAlbum.setText("Album");
        pnlDatos.add(lblAlbum);

        tbtnLike.setText("C");

        tbtnShuffle.setText("S");

        btnBack.setText("<");

        btnPlay.setText("PLAY");

        btnNext.setText(">");

        btnBucle.setText("R");

        lblVol.setText("jLabel4");

        lblDuracion.setText("00:00");

        lblTime.setText("00:00");

        javax.swing.GroupLayout PlayerInferiorLayout = new javax.swing.GroupLayout(PlayerInferior);
        PlayerInferior.setLayout(PlayerInferiorLayout);
        PlayerInferiorLayout.setHorizontalGroup(
            PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerInferiorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblCaratula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(tbtnLike, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayerInferiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addComponent(tbtnShuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBucle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sldTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVol, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PlayerInferiorLayout.setVerticalGroup(
            PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerInferiorLayout.createSequentialGroup()
                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCaratula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                        .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PlayerInferiorLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(tbtnLike))
                            .addGroup(PlayerInferiorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PlayerInferiorLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sldVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbtnShuffle)
                                        .addComponent(btnBucle)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PlayerInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDuracion)
                                    .addComponent(lblTime))))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlCentral.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(PlayerInferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArbolABBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbolABBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArbolABBActionPerformed

    private void btnBlibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlibliotecaActionPerformed
       java.awt.CardLayout layout = (java.awt.CardLayout) pnlCentral.getLayout();
        
        // Mostramos la carta usando el "Apodo" que le pusimos arriba
        layout.show(pnlCentral, "CARTA_BIBLIOTECA");
    }//GEN-LAST:event_btnBlibliotecaActionPerformed

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PlayerInferior;
    private javax.swing.JPanel SideBar;
    private javax.swing.JPanel TopBar;
    private javax.swing.JButton btnAVL;
    private javax.swing.JButton btnArbolABB;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBliblioteca;
    private javax.swing.JToggleButton btnBucle;
    private javax.swing.JButton btnColaReproduccion;
    private javax.swing.JButton btnEncriptacion;
    private javax.swing.JButton btnEstadistica;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlaylist;
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblCaratula;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblLupa;
    private javax.swing.JLabel lblSmart;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVol;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JSlider sldTime;
    private javax.swing.JSlider sldVolumen;
    private javax.swing.JToggleButton tbtnLike;
    private javax.swing.JToggleButton tbtnShuffle;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
